### ISSUE TITLE
Missing GPG Key

### ISSUE THREAD

**Issue by S7venLights** [rpmfusion-infra/ansible-rpmfusion#3]
More on this issue here: https://github.com/coreos/rpm-ostree/issues/4250
*Edit I found a work around fix, see comment 3

After re-basing from Fedora silverblue to Kionite.
I'm unable to do updates using

`rpm-ostree upgrade`
result:
```
Updating metadata for 'rpmfusion-nonfree-nvidia-driver'... done
error: Updating rpm-md repo 'rpmfusion-nonfree-nvidia-driver': Failed to download gpg key for repo 'rpmfusion-nonfree-nvidia-driver': Curl error (37): Couldn't read a file:// file for file:///usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-37 [Couldn't open file /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-37]
```

In order to rebase I had to do the following:
`rpm-ostree uninstall rpmfusion-free-release-36-1.noarch rpmfusion-nonfree-release-36-1.noarch`
Restart and then run your desired rebase, eg:
`rpm-ostree rebase fedora:fedora/37/x86_64/kinoite`
Finally reinstall rpm fusion:
`rpm-ostree install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-37.noarch.rpm https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-37.noarch.rpm`

although should I have actually done this to reinstall? :
`sudo rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm`

I tried to use this https://rpmfusion.org/keys to do this` rpm-ostree install distribution-gpg-keys `
but it failed with the same error.

I will try remove and reinstall as suggested on the website,

In any case let me know if there's a solution.

**Comment by S7venLights** [comment]
Removing rpm fusion worked, but now I can't reinstall as I'm still met by the same error.
I will rollback to a previous image of my system to get rpm fusion back

But I can't do any system updates please help

**Comment by S7venLights** [comment]
Okay I fixed it by downloading the gpg keys from https://rpmfusion.org/keys#Obsolete_Keys
Then using terminal to copy them to this directory: /etc/yum.repos.d/

In that same directory, I edited and replaced the 'rpmfusion-nonfree-nvidia-driver.repo' file to point to /etc/yum.repos.d/ where the gpg keys were.

I'm guessing the issue was caused by Fedora silverblues read only file system, not allowing rpm fusion to put gpg files at /usr/share/distribution-gpg-keys since I saw that directory never existed

**Comment by leigh123linux** [comment]
File the issue against silverblue as we don't support it.
